/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ceccigiuliameteo;

/**
 *
 * @author alice
 */
public class FrameMeteo extends javax.swing.JFrame {

    /**
     * Creates new form FrameMeteo
     */
    public FrameMeteo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCitta = new javax.swing.JLabel();
        txtCitta = new javax.swing.JTextField();
        btnPrevisione = new javax.swing.JButton();
        btnAttuale = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxStampa = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 480));
        setMinimumSize(new java.awt.Dimension(700, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCitta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCitta.setText("Città:");
        getContentPane().add(lblCitta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 115, 60, 40));
        getContentPane().add(txtCitta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 330, 20));

        btnPrevisione.setText("Previsioni a 5 giorni");
        btnPrevisione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevisioneActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevisione, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 380, 40));

        btnAttuale.setText("Meteo Attuale");
        btnAttuale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttualeActionPerformed(evt);
            }
        });
        getContentPane().add(btnAttuale, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 380, 40));

        atxStampa.setColumns(20);
        atxStampa.setRows(5);
        jScrollPane1.setViewportView(atxStampa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 380, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/meteo-09-01-2026-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -130, 660, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/cieloblu.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(700, 480));
        jLabel1.setMinimumSize(new java.awt.Dimension(700, 480));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 480));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevisioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevisioneActionPerformed

        String citta = txtCitta.getText();

        try {
            RootPrevisioni meteo = ChiamataServer.getPrevisione(citta);

            atxStampa.append("\n🌤 PREVISIONI METEO\n");
            atxStampa.append("Città: " + meteo.city.name + "\n\n");

            for (int i = 0; i < meteo.list.size(); i++) {
                // Prendo l'elemento corrente
                List item = meteo.list.get(i);
                atxStampa.append("🕒 " + item.dt_txt + "\n");
                atxStampa.append("Temp: " + item.main.temp + "°C\n");
                atxStampa.append("Umidità: " + item.main.humidity + "%\n");
                atxStampa.append("Descrizione: " + item.weather.get(0).description + "\n");
                atxStampa.append("Nuvole: " + item.clouds.all + "%\n");
                atxStampa.append("Vento: " + item.wind.speed + " km/h\n");
                atxStampa.append("\n");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrevisioneActionPerformed

    private void btnAttualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttualeActionPerformed

        String citta = txtCitta.getText();

        try {
            Root meteo = ChiamataServer.getMeteoAttuale(citta);

            atxStampa.append("\n🌤 METEO ATTUALE \n");
            atxStampa.append("Città: " + meteo.name + "\n");
            atxStampa.append("Temperatura: " + meteo.main.temp + "°C \n");
            atxStampa.append("Umidità: " + meteo.main.humidity + "% \n");
            atxStampa.append("Descrizione: " + meteo.weather.get(0).description + "\n");
            atxStampa.append("Coordinate: " + meteo.coord.lon + " ; " + meteo.coord.lat + "\n");
            atxStampa.append("Velocità vento: " + meteo.wind.speed + "km/h \n");
            atxStampa.append("Nuvole: " + meteo.clouds.all + "% \n");

        } catch (Exception e) {
            System.out.println("Errore nel recupero del meteo.");
        }
    }//GEN-LAST:event_btnAttualeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMeteo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxStampa;
    private javax.swing.JButton btnAttuale;
    private javax.swing.JButton btnPrevisione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCitta;
    private javax.swing.JTextField txtCitta;
    // End of variables declaration//GEN-END:variables
}
