/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ceccigiuliameteo;

/**
 *
 * @author alice
 */
public class FrameMeteo extends javax.swing.JFrame {

    /**
     * Creates new form FrameMeteo
     */
    public FrameMeteo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCitta = new javax.swing.JLabel();
        txtCitta = new javax.swing.JTextField();
        btnPrevisione = new javax.swing.JButton();
        btnAttuale = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxStampa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCitta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCitta.setText("Città:");

        btnPrevisione.setText("Previsioni a 5 giorni");
        btnPrevisione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevisioneActionPerformed(evt);
            }
        });

        btnAttuale.setText("Meteo Attuale");
        btnAttuale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttualeActionPerformed(evt);
            }
        });

        atxStampa.setColumns(20);
        atxStampa.setRows(5);
        jScrollPane1.setViewportView(atxStampa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(txtCitta, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblCitta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(btnAttuale, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(btnPrevisione, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(txtCitta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblCitta))
                    .addGap(9, 9, 9)
                    .addComponent(btnAttuale, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btnPrevisione, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevisioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevisioneActionPerformed

        String citta = txtCitta.getText();

        try {
            RootPrevisioni meteo = ChiamataServer.getPrevisione(citta);

            atxStampa.append("\n🌤 PREVISIONI METEO\n");
            atxStampa.append("Città: " + meteo.city.name + "\n\n");

            for (int i = 0; i < meteo.list.size(); i++) {
                // Prendo l'elemento corrente
                List item = meteo.list.get(i);
                atxStampa.append("🕒 " + item.dt_txt + "\n");
                atxStampa.append("Temp: " + item.main.temp + "°C\n");
                atxStampa.append("Umidità: " + item.main.humidity + "%\n");
                atxStampa.append("Descrizione: " + item.weather.get(0).description + "\n");
                atxStampa.append("Nuvole: " + item.clouds.all + "%\n");
                atxStampa.append("Vento: " + item.wind.speed + " km/h\n");
                atxStampa.append("\n");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrevisioneActionPerformed

    private void btnAttualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttualeActionPerformed

        String citta = txtCitta.getText();

        try {
            Root meteo = ChiamataServer.getMeteoAttuale(citta);

            atxStampa.append("\n🌤 METEO ATTUALE \n");
            atxStampa.append("Città: " + meteo.name + "\n");
            atxStampa.append("Temperatura: " + meteo.main.temp + "°C \n");
            atxStampa.append("Umidità: " + meteo.main.humidity + "% \n");
            atxStampa.append("Descrizione: " + meteo.weather.get(0).description + "\n");
            atxStampa.append("Coordinate: " + meteo.coord.lon + " ; " + meteo.coord.lat + "\n");
            atxStampa.append("Velocità vento: " + meteo.wind.speed + "km/h \n");
            atxStampa.append("Nuvole: " + meteo.clouds.all + "% \n");

        } catch (Exception e) {
            System.out.println("Errore nel recupero del meteo.");
        }
    }//GEN-LAST:event_btnAttualeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMeteo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxStampa;
    private javax.swing.JButton btnAttuale;
    private javax.swing.JButton btnPrevisione;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCitta;
    private javax.swing.JTextField txtCitta;
    // End of variables declaration//GEN-END:variables
}
